### ISSUE TITLE
Share data with wheelmap.org

### ISSUE THREAD

**Issue by stefangrotz** [arduina/access_map#4]
Love this project. I think there could be a lot of synergies with the project http://wheelmap.org, a map based on Openstreetmap which shows tram stations, restaurants and other places that are accessible for people in wheelchairs. 

Maybe these two projects can join forces.

**Comment by k-nut** [comment]
Just [pinged wheelmap on twitter](https://twitter.com/notknut/status/745249284577177600). Let's see what they think.
